
const {
  summarizeNotes,
  recommendNextStep,
  scoreLeadLLM,
} = require('./llm.service')

/**
 * 1. Lead Scoring using Groq LLM
 * @param {Object} lead
 * @returns {Object} { score, reason }
 */
exports.scoreLead = async (lead) => {
  try {
    const result = await scoreLeadLLM(lead)

    // Expecting LLM to return something like:
    // "Score: 78\nReason: Strong budget, fast timeline."
    const scoreMatch = result.match(/score[: ]+(\d+)/i)
    const reasonMatch = result.match(/reason[: ]+(.*)/i)

    return {
      score: scoreMatch ? Number(scoreMatch[1]) : 50,
      reason: reasonMatch ? reasonMatch[1].trim() : 'Generated by LLM',
      raw: result,
    }
  } catch (err) {
    console.error('LLM lead scoring failed:', err)
    return { score: 50, reason: 'Fallback scoring due to LLM error' }
  }
}

/**
 * 2. Summarize CRM Notes using Groq LLM
 * @param {string} text
 * @returns {string}
 */
exports.summarizeNote = async (text) => {
  try {
    if (!text || text.trim().length === 0) return ''

    const summary = await summarizeNotes(text)
    return summary
  } catch (err) {
    console.error('LLM summarization failed:', err)
    return text.slice(0, 200) + '...'
  }
}

/**
 * 3. Recommend Next Action for a Lead / Client
 * @param {Object} lead
 * @returns {string}
 */
exports.recommendNextStep = async (lead) => {
  try {
    const recommendation = await recommendNextStep(lead)
    return recommendation
  } catch (err) {
    console.error('LLM recommendation failed:', err)
    return 'Unable to generate recommendation'
  }
}
